name: Execute

on:
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: self-hosted 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Execute Python script
        run: python3 main.py